### ISSUE TITLE
Is it still being worked on?

### ISSUE THREAD

**Issue by ErikKrause** [jimporter/mail-summaries#1] opened 2022-09-29 21:59 UTC
I found Mail Summaries indispensable...

**Comment by jimporter** [comment] 2022-09-30 00:15
Well, the project isn't dead, but it's taking a long nap. The basics of the folder summary should work fine for the most part, but the biggest stumbling block for me is getting context menus working again (unfortunately, Thunderbird changed things in response to a Firefox change, which broke this). That's particularly annoying, since I use the "Filter by Sender" context item under "Top Authors" a *lot*.

Longer term, I'm hoping the Thunderbird team just merges the code into Thunderbird proper. They've expressed some interest in doing so, although I don't have time to help them out with that beyond providing some advice.

**Comment by ErikKrause** [comment] 2022-09-30 10:04
A short search revealed this: [https://webextension-api.thunderbird.net/en/102/menus.html](https://webextension-api.thunderbird.net/en/102/menus.html), but I guess you know that already...

**Comment by jimporter** [comment] 2022-09-30 16:05
Yeah, unfortunately the problem is that the particular `<browser>` element the extension uses had its security context changed in a way that makes it hard (impossible?) to set up a context menu through the add-on. Most of the existing code is running in a privileged add-on context, but it's still tough to hotfix things like this...

The "easy" solution is just to make a new in-content context menu with regular HTML, but that's got some limitations and would probably require some additional scaffolding.

**Comment by ErikKrause** [comment] 2022-09-30 21:28
I'm not a mozilla developer at all, but I [found this](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Context_menu_items), saying: "You manage context menu items programmatically, using the [contextMenus](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus) API. However, you need to request the contextMenus permission in your manifest.json to be able to take advantage of the API."

**Comment by jimporter** [comment] 2022-10-01 01:15
The WebExtension (or MailExtension) APIs actually don't matter here, since I just bypass that and use the older-style add-on code, since Mail Summaries would require quite a few MailExtension APIs that don't exist, and it was easier to adapt the old code this way.

**Comment by ErikKrause** [comment] 2022-10-03 20:02
What would I need to do to test it? Does it work with TB 102? (I am extremely brave ;-))

**Comment by jimporter** [comment] 2022-10-03 20:05
If you just want to use the add-on as-is, the easiest method would be to clone this repo, run `make package`, and then install the `.xpi` file it generated. You can also load the add-on temporarily without building by using Thunderbird's equivalent of `about:debugging`: Hamburger -> Tools -> Developer Tools -> Debug Addons

**Comment by jimporter** [comment] 2022-10-03 20:43
I pushed some fixes to get this minimally functional again on 102 (it mostly worked on 91), but that sort of underscores the problem here: it's a pain trying to keep up with the changes made in Thunderbird, and the MailExtension APIs just don't have the features this add-on needs, so switching to that isn't really feasible (at least, not without upstreaming a lot of new APIs, which I just don't have time for).

(Note: the CSS is still pretty busted since Thunderbird 102 deleted a CSS file that Mail Summaries previously relied upon, so I'll need to fix that too.)

**Comment by ErikKrause** [comment] 2022-10-03 21:10
Hmm, I'm seeing this
![Clipboard05](https://user-images.githubusercontent.com/6303830/193683128-84a1bddc-6cfd-4e59-b39a-f5fa1bc8afcf.jpg)
There are 20 messages in the folder...

**Comment by jimporter** [comment] 2022-10-03 21:26
That's partly the aforementioned busted CSS, but there's probably an exception being thrown somewhere too.

**Comment by jimporter** [comment] 2022-10-03 21:38
Note: Don't bother testing this out too much yet, since I already have an idea of what I need to do to get this working properly (when I said "minimally functional" I really meant it: prior to the latest commits, the add-on didn't even load :/). I'm going to close this and file some new issues to track what needs to be done to at least get it to where it was the last time I left off.

**Closed as completed by jimporter** 2022-10-03 21:38 UTC

**Comment by jimporter** [comment] 2022-10-03 21:43
I think I fixed this *just* enough that it's usable now, but it'll definitely need more work.

**Comment by ErikKrause** [comment] 2022-10-03 21:56
wow! looks good!

**Comment by jimporter** [comment] 2022-10-11 23:57
@ErikKrause Since you're following this, I thought I'd let you know that my plan is to fix issues #2 and #3 and then tag 5.0b1 and add a pre-built .xpi file to this project page. Then once I get context menus working, I'll tag the final release for 5.0 and upload it to TB's add-on repository.

I'm not sure what I'll do about account summaries. I never found them all that useful, so maybe it's not worth fixing them up...

**Comment by ErikKrause** [comment] 2022-10-12 09:05
> I'm not sure what I'll do about account summaries.

Well, I find the usage statistics very useful, especially since I have multiple accounts.
